### PR TITLE
✨ Check for config in /usr/share/sunpaper/

### PR DESCRIPTION
**Pull request by benjamin-voisin**
I was trying to make an AUR package for sunpaper, but add some difficulties with the configuration. As packages are installed system wide, they cannot write anything into ~/.config/sunpaper.

With this modification, if there is no config files, it also try to find a default one in /usr/share/sunpaper, and copy it into the ~/.config/sunpaper directory. So the config file is initialized after the first run.

### CODE REVIEW

**Comment by hexive** [comment]
thanks for working on the AUR package! that's been in my todo list for years at this point!

so the AUR installer would put a config at /usr/share/sunpaper/config? would you like that file to sit in the repo somewhere also?

not that sunpaper is in any kind of active development, but I think my apprehension about external configs was always how to handle them if there were config changes in the future. problem for another day, perhaps?

I'm happy to merge this as-is or maybe update with the the config file text if that's helpful to you.

**Comment by benjamin-voisin** [comment]
I have a `sed` command that extract de config part from the script, but it would be much cleaner with a dedicated file for sure ! I've just added that.

**Comment by hexive** [comment]
last thing -- let's put the config file in an AUR/ directory so we don't confuse people. should have thought of this with my last message. I apologize.

**Comment by hexive** [comment]
cool. thanks again. please let me know if you need anything else from me.

pls drop me a note when you get it all working and I'll update the readme and give the whole thing a version bump.

**Comment by benjamin-voisin** [comment]
@hexive Just so you know, it is now published [here](https://aur.archlinux.org/packages/sunpaper) ! It might be good to add a line to the Readme to mention it.

**Comment by hexive** [comment]
This is great. I really appreciate it!
https://github.com/hexive/sunpaper/releases/tag/v2.1

**Pull request merged**
